services:
  bot:
    build: .
    env_file:
      - .env
    restart: always
  db:
    image: postgres:15
    volumes:
      - ./schemes:/docker-entrypoint-initdb.d:ro
      - db_vol:/var/lib/postgresql/data
    env_file:
      - .env
    restart: always

volumes:
  db_vol:
